### ISSUE TITLE
Data loader for YAML

### ISSUE THREAD

**Issue by garlontas** [PickwickSoft/pystreamapi#71]
# YAML data loader

Currently, we have a data loader for CSV files. It works by converting each data set (each row) to a `namedtuple`.

We need sth similar for YAML. Note that type conversion should be done as efficient as possible (see issue #63 for more information).

The loader should also handle non-consistent data, such as the YAML below:
```yml
- name: Joe Doe
  position: Vice President
  children:
    - name: Jim Doe
    - name: Kim Doe
- class: Mammalia
  order: Carnivora
  family: Canidae
  genus: Canis

``` 
Here, a `LazyFileIterable` containing two differently structured `namedtuples` should be created.

You can view the implementation for CSV [here](https://github.com/PickwickSoft/pystreamapi/blob/main/pystreamapi/loaders/__csv/__csv_loader.py).

You can view the issue for the JSON loader here: #70
