### ISSUE TITLE
Data loader for TOML

### ISSUE THREAD

**Issue by garlontas** [PickwickSoft/pystreamapi#73]
# TOML data loader

Currently, we have a data loader for CSV files. It works by converting each data set (each row) to a `namedtuple`.

We need sth similar for TOML. Note that type conversion should be done as efficient as possible (see issue #63 for more information).

The loader should also handle non-consistent data, such as the TOML below:
```toml
[[employees.employee]]
name = "John Doe"
position = "Software Engineer"
salary = 80_000
children = 2

[[employees.employee]]
name = "Alice Smith"
position = "Network Administrator"
salary = 75_000
children = 1

[[employees.employee]]
name = "Bob Johnson"
experience = "Database"
wage = 82_000
car = "Audi"
``` 
Here, a `LazyFileIterable` containing three differently structured `namedtuples` should be created.

You can view the implementation for CSV [here](https://github.com/PickwickSoft/pystreamapi/blob/main/pystreamapi/loaders/__csv_loader.py).

You can view the issue for the JSON loader here: #70 

You can view the issue for the YAML loader here: #71

You can view the issue for the XML loader here: #72
